name: Build and release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install core/libs
        run: |
             arduino-cli core update-index
             arduino-cli core install "arduino:avr"
             arduino-cli lib install "FastLED@3.4.0" "Adafruit BMP280 Library@2.3.0"

      - name: Compile configs
        run: ./build.sh --all

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: Chackout
        uses: actions/checkout@v2

      - name: Check version
        run: |
              git fetch --tags
              file_ver=$(awk '/VERSION:/ {print $3}' LEDController.ino)
              ch_ver=$(awk -F'[][]' '/\[v[0-9.]+\]/ {print $2; exit}' CHANGELOG.md)
              git_vers=$(git describe --tags --always $(git rev-list --tags))

              echo "Latest git tag:    ${git_vers%%$'\n'*}"
              echo "File version:      ${file_ver}"
              echo "Changelog version: ${ch_ver}"

              if [[ $file_ver != $ch_ver || $git_vers =~ $file_ver ]]; then echo "Version issue!"; exit 1; fi

  release:
    needs: [build, check_version]
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2

      - name: Generate changelog
        run: awk '/^## / {if (p) {exit}; {p=1}} p' CHANGELOG.md > latest-CHANGELOG.md

      - name: Get version
        run: echo "version=$(awk '/VERSION:/ {print $3}' LEDController.ino)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.version }}
          body_path: latest-CHANGELOG.md
          files: build/*
